"""
Preview endpoints — everything the frontend needs to render a generated site
the way the public renderer will, before anything is pushed.

`POST /api/preview/layout` — menus + wrapped header/footer for a GeneratedSite

The frontend's preview renderer resolves `menu` elements against `menus[]` and
reads header `behavior` for overlay/shrink, exactly as webtree-public does with
the layout the CMS serves it. This endpoint hands back the same payload the push
writes (same builder, see services/menu_builder.build_layout_payload), so the
preview and the published site start from identical input.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException

from app.models.builder_schema import GeneratedSite
from app.services.menu_builder import build_layout_payload

router = APIRouter(prefix="/api/preview", tags=["preview"])


@router.post("/layout")
async def preview_layout(site: GeneratedSite) -> dict[str, Any]:
    """Return the layout payload this site would push: menus + header + footer."""
    try:
        payload = build_layout_payload(site)
    except ValueError as exc:
        # A site without header/footer schema was never generated by
        # plan_to_site() — a client bug, not a server fault.
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return {
        "menus": payload.menus,
        "header": payload.header,
        "footer": payload.footer,
    }
